### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by gjedeer** [alufers/inpost-cli#1]
Hey,

I can't wait to use it!

I'm getting the error below - I guess that's because I'm using a wrong version of Go - it would be nice if your instructions included the minimum version.

```
➜  ~ go get -u github.com/alufers/inpost-cli
package context: unrecognized import path "context" (import path does not begin with hostname)
package github.com/mdp/qrterminal/v3: cannot find package "github.com/mdp/qrterminal/v3" in any of:
        /usr/lib/go-1.6/src/github.com/mdp/qrterminal/v3 (from $GOROOT)
        /home/gdr/tmp/src/github.com/mdp/qrterminal/v3 (from $GOPATH)
        /tmp/src/github.com/mdp/qrterminal/v3
package github.com/urfave/cli/v2: cannot find package "github.com/urfave/cli/v2" in any of:
        /usr/lib/go-1.6/src/github.com/urfave/cli/v2 (from $GOROOT)
        /home/gdr/tmp/src/github.com/urfave/cli/v2 (from $GOPATH)
        /tmp/src/github.com/urfave/cli/v2
```

**Comment by alufers** [comment]
Hi!
This program uses go modules, which were added in Go 1.12 and that makes 1.12 the minimal required Go version, although I recommend using the latest stable release - 1.15.6 at the time of writing (December 2020). 

If for whatever reason you cannot install Go 1.12 there binaries available for various operating systems and architectures at the [releases page](https://github.com/alufers/inpost-cli/releases).

Thanks for the info, I will add this information to the Readme.

Kind regards,
Albert
