### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NerraT** [alufers/inpost-cli#5]
![inpost](https://user-images.githubusercontent.com/98057317/150210346-646231dc-95ec-4d52-b081-41188025735a.png)
Hello, I have this problem when I want to login :( Could you please help me?

**Comment by alufers** [comment]
Oh it looks like a problem with Windows line endings. I haven't tested the program on Windows yet. I will release a fix in a moment.

**Comment by alufers** [comment]
I have created a new version which should fix the issue. You can download it here: https://github.com/alufers/inpost-cli/releases/tag/1.0.2
