### ISSUE TITLE
Allow for specifying config path with a command line parameter

### ISSUE THREAD

**Issue by ptrcnull** [alufers/inpost-cli#6]
Example:
```
$ inpost-cli --config some_file.json ls
```

**Comment by robertzPL** [comment]
excelent idea.

**Comment by alufers** [comment]
Hi!

I have added this option, but additionally I added an option to use multiple accounts with one config file, so for most use-cases you can just run `inpost-cli login` multiple times to have multiple phone numbers logged-in.

**Comment by robertzPL** [comment]
thanks but an option to use multiple accounts with one config file not work
